version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.9"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    environment:
      SHELL: /bin/zsh