name: Build container and push CI

on:
  push:
    branches:
     - main

env:
  GITHUB_SHA: ${{ github.sha }}
  REPOSITORY: aws-sentinel-connector
  REGISTRY: public.ecr.aws/cds-snc

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/aws-sentinel-connector-layer-apply
          role-session-name: SentinelGitHubActions
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be # v1.5.3
        with:
          registry-type: public

      - name: Build docker image
        working-directory: ./layer
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$GITHUB_SHA .

      - name: Push docker image to AWS ECR
        run: |
          docker push $REGISTRY/$REPOSITORY:$GITHUB_SHA

      - name: Generate $REPOSITORY/docker SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@f0d609b2a8f51dbb4b1760b02a35fb1aadbae7f1 # v1.1.6
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          docker_image: $REGISTRY/$REPOSITORY:$GITHUB_SHA
          project_name: aws-sentinel-conector-layer/docker
          project_type: docker