name: Build container

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      
      - name: Build docker image
        working-directory: ./layer
        run: |
          docker build -t aws-sentinel-connector:test .

      - name: Generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@f0d609b2a8f51dbb4b1760b02a35fb1aadbae7f1 # v1.1.6
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          docker_image: aws-sentinel-connector:test
          project_name: aws-sentinel-conector-layer/docker
          project_type: docker
