name: Build container

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      
      - name: Build docker image
        working-directory: ./layer
        run: |
          docker build -t aws-sentinel-connector:test .
