name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.0.3
  TERRAGRUNT_VERSION: 0.31.1
  TF_VAR_lambda_list_layers_assume_principals: ${{ secrets.LAMBDA_LIST_LAYERS_ASSUME_PRINCIPALS }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ca-central-1
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/aws-sentinel-connector-layer-apply
          role-session-name: SentinelGitHubActions
          aws-region: "ca-central-1"

      - name: Build layer
        working-directory: layer
        run: |
          make build

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terragrunt apply --terragrunt-non-interactive -auto-approve
