name: Terraform plan
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.0.3
  TERRAGRUNT_VERSION: v0.31.1
  CONFTEST_VERSION: 0.27.0

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: terraform

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@82586e7b242a8035c7d02e7519341eb9348fe195

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/AWSSentinelConnectorLayerTerraformReadOnlyRole
          role-session-name: SentinelGitHubActions
          aws-region: "ca-central-1"

      - name: Build layer
        working-directory: layer
        run: |
          make build

      - name: Terraform Plan ${{ matrix.module }}
        uses: cds-snc/terraform-plan@v2
        with:
          comment-delete: true
          comment-title: Plan for ${{ matrix.module }}
          directory: ./${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
